### ISSUE TITLE
Composite.PackageInstaller.exe Error: 0 : [ServiceBusListener] System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by Mathieu265** [Orckestra/BetterRetail#29]
I am having issue deploying the solution. After i ran ./install.ps1 -env=int i get all green messages in the administrator powershell telling the task have succeeded and then a webpage (https://composer-c1-betterretail.develop.orckestra.cloud/Composite/top.aspx)  open with this message 
```
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
```

I tried to go in the deployment folder and give the iis_iusrs the full permission to the web.config but now i get an infinite loading screen with the same error message.

I'll explain my full walkthroug so far:

1. Cloned the repo and selected the dev branch
2. Ran the build.ps1
3. Changed the certificate in the install.cake to be localhost
```
var certificate = GetCertificate("localhost");
```
4. Changed some value in the parameters.json and parameters.int.json. Here they are:
**Parameter.json**:
```
{
  "ocs-cm-hostName": "",
  "ocsAuthToken": "",

  "em-branch": "4.9.0",
  "adminName": "",
  "adminPassword": "",
  "adminEmail": "build-bot@orckestra.com",

  "C1Url": "https://github.com/Orckestra/C1-CMS-Foundation/releases/download/v6.9/C1.CMS.6.9.zip",

  "websiteSuffix": "{{new System.IO.DirectoryInfo(rootPath).Name}}",
  "websiteName": "composer-c1-{websiteSuffix}.develop.orckestra.cloud",
  "websiteUrl": "https://{websiteName}",

  "setupDescription": "{{$\"{rootPath}/build/configuration/SetupDescription.xml\"}}",
  "setupDescriptionSecondary": "{{$\"{rootPath}/build/configuration/SetupDescriptionSecondary.xml\"}}",
  "baseCulture": "en-CA",
  "occ-hostName": "occ-dev-localdeployment",
  "serviceBus-keyName": "RootManageSharedAccessKey",
  "serviceBus-key": "",
  "serviceBus-topicPrefix": ""
}
```
**parameters.int.json**:
```
{
  "environments":{
    "int": {
      "adminName": "admin",
      "adminPassword": "123456",
      "ocs-cm-hostName": "ocs-cm-dev-localdeployment",
      "ocsAuthToken": ""
    }
  }
}
```
5. Got the error 
```
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Config Error | Cannot read configuration file due to insufficient permissions
C:\Users\Mathieu\Desktop\CDMV\BetterRetail\deployment\Website\web.config
```
and then tried to add the permission to the iis user but now got infinite loading.
I also have an error while doing the .\Install.ps1 -env=int
```
========================================
Install-Secondary-Packages
========================================
Inject Package Installer to Website
Language: 'en-CA'
Composite.PackageInstaller.exe Information: 0 : [LegacySerializedEntityTokenUpgrader] Finished updating serialized tokens for data type 'Composite.Data.Types.IFlowInformation'. Rows: 0, Updated: 0, Errors: 0
Composite.PackageInstaller.exe Information: 0 : [LegacySerializedEntityTokenUpgrader] Finished updating serialized tokens for data type 'Composite.Data.Types.IUserActivePerspective'. Rows: 0, Updated: 0, Errors: 0
Composite.PackageInstaller.exe Information: 0 : [LegacySerializedEntityTokenUpgrader] Finished updating serialized tokens for data type 'Composite.Data.Types.IUserGroupActivePerspective'. Rows: 21, Updated: 15, Errors: 0
Composite.PackageInstaller.exe Information: 0 : [LegacySerializedEntityTokenUpgrader] Finished updating serialized tokens for data type 'Composite.Data.Types.IUserGroupPermissionDefinition'. Rows: 3, Updated: 3, Errors: 0
Composite.PackageInstaller.exe Information: 0 : [LegacySerializedEntityTokenUpgrader] Finished updating serialized tokens for data type 'Composite.Data.Types.IUserPermissionDefinition'. Rows: 0, Updated: 0, Errors: 0
Composite.PackageInstaller.exe Error: 0 : [ServiceBusListener] System.ArgumentNullException: Value cannot be null.
Parameter name: sharedAccessKey
   at Microsoft.ServiceBus.SharedAccessSignatureTokenProvider..ctor(String keyName, String sharedAccessKey, Func`2 customKeyEncoder, TimeSpan tokenTimeToLive, TokenScope tokenScope)
   at Microsoft.ServiceBus.TokenProvider.CreateSharedAccessSignatureTokenProvider(String keyName, String sharedAccessKey)
   at Orckestra.ExperienceManagement.Configuration.ServiceBus.ServiceBusListener.<Run>d__11.MoveNext()
```

**Comment by Mathieu265** [comment]
Solved my issue, there was in fact 2 kind of problems.

**First, the console error**
I needed to add some configuration for the installation error

```
  "occ-hostName": "occ-dev-localdeployment",
  "serviceBus-keyName": "RootManageSharedAccessKey",
  "serviceBus-key": "",
  "serviceBus-topicPrefix": ""
```
Contacted orckestra support for our serviceBus information and added these to the config ran a ./Build.ps1 and then the install script and the error was gone.

**Second, the permission problem**
This was purely an IIS configuration problem had to add permission on the whole repo folder to the user _IIS AppPool\composer-c1-BetterRetail.develop.orckestra.cloud_ you could also just give the permission to the _IIS_IUSRS_ group instead it should also work.

I also got the _**Config Error: This configuration section cannot be used at this path**_ error. Solved this by with this thread https://stackoverflow.com/questions/9794985/config-error-this-configuration-section-cannot-be-used-at-this-path
